### ISSUE TITLE
Look for packages to use in the application and plan out user interface

### ISSUE THREAD

**Issue by tuckermiles70** [cs340-20/Whirl#12]

**Comment by mattmohandiss** [comment]
Packages:
- [Firebase Auth](https://pub.dev/packages/firebase_auth)
- [Firebase Firestore](https://pub.dev/packages/cloud_firestore)
- [Google Maps](https://pub.dev/packages/google_maps_flutter)
- [Location](https://pub.dev/packages/location)
- [Location Picker](https://pub.dev/packages/google_map_location_picker)
